server:
  port: 7027

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 5678
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: mall-auth2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: "*"


# 自定义授权的应用
kq:
  oauth2:
    clients[0]: # 第一个应用，要是有多个clients[1]、clients[2]等等
      clientId: kq-mall
      clientSecret: 123456
      accessTokenValiditySeconds: 7200
      authorizedGrantTypes: refresh_token,password # authorization_code目前允许密码模式和刷新token,不允许授权码模式,
      scopes: all,read,write